### PR TITLE
Allow self signed certificate ignoring ssl checks

### PR DESCRIPTION
**Pull request by luisza**
This PR, allow to ignore ssl check on proxy server, so self signed certificates can handle on proxy.

Use example 

```
   driver = webdriver.Chrome('chromedriver',
                              seleniumwire_options={'ssl_verify': False})
```

### CODE REVIEW

**Comment by wkeeling** [comment]
@luisza many thanks for contributing this PR.

Just so that I fully understand, can you just describe the problem that this change addresses?

Selenium Wire will already tell the browser to accept invalid certificates (via the `acceptInsecureCerts` capability for Chrome). However, your PR looks to address the verification between Selenium Wire and the _upstream_ server. Is that correct?

**Comment by luisza** [comment]
Hi, 
Using Selenium Wire I saw that request are made through internal proxy server (proxy2) on Linux, that always make a ssl check and response as error when ssl is not valid.   Because  request is processed on proxy part acceptInsecureCerts on Browser has not effect and show an empty page.

**Comment by wkeeling** [comment]
Thanks @luisza . Are there any particular circumstances where you see the invalid SSL response - e.g. are you using a upstream proxy in your test (a proxy upstream of Selenium Wire's own proxy), or is there a specific website or test configuration where you see the error occur?

**Comment by wkeeling** [comment]
@luisza I completely understand the need for this now. I will resolve the conflicts and then merge this change. Many thanks for contributing the PR.

**Comment by wkeeling** [comment]
This change has been implemented and merged separately due to the code diverging since this PR was created.

**Pull request closed without merging**
