### PR TITLE
feat: Ability to set scope for proxy to capture request/response

### PR DESCRIPTION
**Pull request by idxn**

### CODE REVIEW

**Comment by idxn** [comment]
@wkeeling If you have time, please review. This could speed up the selenium wire as well if we could focus on the request we are interested in only.

**Comment by wkeeling** [comment]
Thanks very much for contributing this PR! Selective request capturing was something that has been talked about in the past but never implemented - until now. I think it's a nice feature, particularly as it could improve performance as you mention - and could also be a useful debugging facility.

**Comment by veerabio** [comment]
@idxn how would one pass the scopes. is it part of the seleniumwire_options?

**Comment by wkeeling** [comment]
@veerabio - you can use the new [scopes](https://github.com/wkeeling/selenium-wire#scoping-request-capture) attribute. This applies request capture to specific URL patterns.

**Pull request merged**
