### PR TITLE
Add ability to modify responses

### LINKED ISSUE #63: [Feature request] Modify request responses
It may be out of the use case for this project, but I think it'd be very useful to write `mitmproxy`-style response handlers to inject various things into the webpage before the page load. Here's a simple `mitmproxy`-style response handler that could be useful. It parses text/html requests that respond with the status code 200 and injects some simple js code.

```
    def response(self, flow):
        # only process 200 responses of html content
        if flow.response.headers['Content-Type'] != 'text/html':
            return
        if not flow.response.status_code == 200:
            return

        # inject the script tag
        parsed_html = html.fromstring(flow.response.text)
        container = parsed_html.head or parsed_html.body
        if container:
            script = builder.SCRIPT('alert("injected")', type='text/javascript')
            container.insert(0, script)
            flow.response.text = parsed_html
```

### PR DESCRIPTION
**Pull request by Mattwmaster58**
With this pull request, I've added the ability to modify responses before they make their way to the browser. This allows advanced users a lot more flexibility with what they can do with `selenium-wire`

Fixes #63

I realize this may be beyond the scope of this project, but I thought I'd try anyway.

### CODE REVIEW

**Comment by wkeeling** [comment]
Many thanks for submitting this PR, and apologies for the delay in relying - been on holiday for a couple of weeks.

I think the premise of this feature is sound, as I think that giving advanced users more flexibility in how Selenium Wire handles requests is a good thing. I'm leaning towards moving the `custom_response_handler` argument into the `seleiumwire_options` however, since it is unlikely to be used that often - and probably doesn't justify being at an elevated level in the API/docs.

I'm happy to merge this PR is it stands and I'll make that minor refactoring in due course.

Many thanks again for your work on this.

**Comment by Mattwmaster58** [comment]
No problem. I agree with the decision to move `custom_response_handler` to an item in `seleiumwire_options` - must have glossed over that before.

I thought I read something earlier that if the Travis CI build succeeded the version would be bumped and the package added to PyPi, however, I'm not seeing it. Did you want to make that small API change before uploading to PyPi to avoid the major version bump that would come with the breaking API changes?

**Comment by wkeeling** [comment]
Travis will deploy to PyPi, but it's configured to do so when a new tag is pushed. As soon as I've made the change I'll create a new tag and push - and the version should update.

Thanks again!

**Comment by Mattwmaster58** [comment]
I can make another PR implementing those features if you'd like (I don't mean to rush you, but I've got some free time). I'd also like to implement some tests for this feature. Thoughts?

**Pull request merged**
